### ISSUE TITLE
request for updated README

### ISSUE THREAD

**Issue by trjate** [atramos/ec2-spotter#3]
Hi Alex, 

This is a very useful application and I wanted to thank you for taking the time to write it.  I was wondering if you could update the README to reflect the current state of master.

I'm having a difficult time figuring out how to set it up.

Best,
Trevor

**Comment by refacktor** [comment]
Thanks I'll try to have a look this week. I need to merge the two branches and some other cleanup.

**Comment by karma0** [comment]
bump.

**Comment by decidedlygray** [comment]
bump

**Comment by burgalon** [comment]
So is the current `master` branch working? Or should I prefer the `classic` branch?

**Comment by refacktor** [comment]
It's all a little bit of a mess, sorry, I have a different private repo for my production version. I'll clean this up as soon as I can.

**Comment by refacktor** [comment]
Clean-up complete!
If you do something interesting with this project, please drop me a note.
Enjoy :-)

**Comment by burgalon** [comment]
Thank you!
