### ISSUE TITLE
Issue and fix using classic

### ISSUE THREAD

**Issue by emrul** [atramos/ec2-spotter#4]
Hi, thank you for this very handy tool.  I have had some issues getting classic to work and have made a couple of changes to make it work in my case:

1. I had to add: `ROOT_VOL_NAME=$2`
2. I had to change the attach volume command to this: `aws ec2 attach-volume --volume-id $PERSISTENT_ROOT_VOLUME --instance-id $INSTANCE_ID --device /dev/sdf`

In ec2spotter-remount-root

Not sure why the original code didn't work for me but the changes I made make it work very well and can be found here: https://github.com/emrul/ec2-spotter/blob/master/classic/ec2spotter-remount-root

**Comment by refacktor** [comment]
Thank you for the fix! I think I accidentally broke this while doing some "code clean-up" without testing. Would you like to make a Pull Request so your ID is linked to the fix?

**Comment by emrul** [comment]
Sure, PR made.  Thanks again for this amazing work.
